<option value="">Select Bank</option>
                      <option value="Access Bank Plc">Access Bank Plc</option>
                      <option value="Citi Bank Nigeria Limited">Citi Bank Nigeria Limited</option>
                      <option value="Coronation Merchant Bank">Coronation Merchant Bank</option>
                      <option value="Diamond Bank Plc">Diamond Bank Plc</option>
                      <option value="Ecobank Nigeria Plc">Ecobank Nigeria Plc</option>
                      <option value="Fidelity Bank Plc">Fidelity Bank Plc</option>
                      <option value="First City Monument Bank Plc">First City Monument Bank Plc</option>
                      <option value="First Bank of Nigeria Limited">First Bank of Nigeria Limited</option>
                      <option value="FBNQuest Merchant Bank">FBNQuest Merchant Bank</option>
                      <option value="FSDH Merchant Bank">FSDH Merchant Bank</option>
                      <option value="Guaranty Trust Bank Plc">Guaranty Trust Bank Plc</option>
                      <option value="Heritage Banking Company Limited">Heritage Banking Company Limited</option>
                      <option value="Keystone Bank Limited">Keystone Bank Limited</option>
                      <option value="Jaiz Bank Plc">Jaiz Bank Plc</option>
                      <option value="Nova Merchant Bank">Nova Merchant Bank</option>
                      <option value="Polaris Bank Limited">Polaris Bank Limited</option>
                      <option value="Providus Bank Limited">Providus Bank Limited</option>
                      <option value="Rand Merchant Bank">Rand Merchant Bank</option>
                      <option value="Stanbic IBTC Bank Plc">Stanbic IBTC Bank Plc</option>
                      <option value="Standard Chartered">Standard Chartered</option>
                      <option value="Sterling Bank Plc">Sterling Bank Plc</option>
                      <option value="SunTrust Bank Nigeria Limited">SunTrust Bank Nigeria Limited</option>
                      <option value="Union Bank of Nigeria Plc">Union Bank of Nigeria Plc</option>
                      <option value="United Bank for Africa Plc">United Bank for Africa Plc</option>
                      <option value="Unity Bank Plc">Unity Bank Plc</option>
                      <option value="Wema Bank Plc">Wema Bank Plc</option>
                      <option value="Zenith Bank Plc">Zenith Bank Plc</option>